#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

TERM=xterm

# Update repositories
sudo apt-get update

#Perform Upgrade
sudo apt-get -y upgrade
sudo apt-get -y dist-upgrade

# Clean + purgeold/obsoleted packages
sudo apt-get -y autoremove

exit 0
